### ISSUE TITLE
Array DataType Should be Saved as an Array

### ISSUE THREAD

**Issue by jefrydco** [jloosli/node-firestore-import-export#14]
### Expected behavior
Array datatype should be saved as an array
### Actual behavior
Array datatype saved as an object
### Steps to reproduce the behavior
Just make a array datatype and import then export it again.

**Comment by jloosli** [comment]
Firebase and Firestore actually store arrays as objects with integers as key names (see https://firebase.googleblog.com/2014/04/best-practices-arrays-in-firebase.html). So when they get exported, they show up as an object, but they should show up as an array after getting imported again.

**Comment by jloosli** [comment]
Actually, I'm having second thoughts on this. I'm going to do some more investigating for Firestore specifically

**Comment by jloosli** [comment]
@jefrydco Thanks for pointing this out. I had incorrectly assumed that Firstore worked the same way as Firebase since my code ended up treating arrays as numeric-key-based objects. Check out v.0.8.1 for the fix. You'll need to export with that version to get the arrays in the output, then import again.

**Comment by jefrydco** [comment]
@jloosli You're welcome, thanks for fixing this issue. Ok, fortunately my database isn't big so I've done it manually. :smile:
