### ISSUE TITLE
JSON file too big ?

### ISSUE THREAD

**Issue by macoapps** [jloosli/node-firestore-import-export#17]
### Expected behavior
Try to upload a big JSON file (~20 MB, ~), full data uploaded in Firestore

### Actual behavior
Got an error :
{ Error: 4 DEADLINE_EXCEEDED: Deadline Exceeded ... }
in client.js:64:15
in client.js:583:15

But i also got the "All done" message ... Strange
Is this a limit because of the size of the file or the time it takes to upload ?

**Comment by jloosli** [comment]
I've had this happen on large exports before. It happens when exceeding the quota for reads/writes in a given collection (see [Firestore Quotas](https://firebase.google.com/docs/firestore/quotas)). On the export side, I catch the error, wait 1 second, then continue with the collection gathering. 

On the import side, for some reason, I haven't seen that yet, but it makes sense that one would run into the same sort of limits. Out of curiosity, did all the data get imported, or were you missing some items? You might want to try running an export of the imported data and compare that to the original export to see if the files match. Let me know what you find out.

**Comment by jloosli** [comment]
Can't replicate. If this is still an issue, please send me some sample data to {github username}@gmail.com

**Comment by amk-dev** [comment]
i've bumped into this exact thing today. i was uploading a subcollection with tonnes of documents and this happened.
