### ISSUE TITLE
Cannot read property 'projectId' of undefined

### ISSUE THREAD

**Issue by shnabz** [jloosli/node-firestore-import-export#26]
### Expected behavior
Import backupFile

### Actual behavior

> TypeError: Cannot read property 'projectId' of undefined
>     at C:\Users\micha\AppData\Roaming\npm\node_modules\node-firestore-import-export\dist\bin\firestore-import.js:69:32

### Steps to reproduce the behavior
`--accountCredentials C:\Users\micha\Downloads\credentials.json --backupFile C:\Users\micha\Desktop\db.json`

**Comment by 2kama** [comment]
I'm facing this same issue....have you found a solution to it?

**Comment by 2kama** [comment]
Okay...i still couldn't figure out what the problem is, but I'd look into in later and suggest a solve.
But I did figure out a temporary solution.

The TypeError comes from the **firestore-import.js:69:32** indicated in the error message.
All you've gotta do is go to that file and comment out line **67 - 69** which holds the variable for your **projectID**. Then create your own **projectID** variable which will will contain the projectID of the database you wanna import to.

`var projectID = "[your projectID]";`

**Comment by barrydrink** [comment]
This issue does not occur if you pass the `-y, --yes` option

**Comment by jloosli** [comment]
Sorry for the late reply...I've been out of town and traveling, so I'll have to take a closer look into this and get back to you.

**Comment by wahono77** [comment]
Just comment pathReference.firestore.projectId
like this 

    var projectID = (pathReference._referencePath && pathReference._referencePath._projectId) ||
        (pathReference.firestore && pathReference.firestore._referencePath && pathReference.firestore._referencePath._projectId); // ||
        //pathReference.firestore.projectId;

**Comment by morandalex** [comment]
@wahono77  please could you explain better ? thanks

**Comment by narimetisaigopi** [comment]
C:\Users\{User Name}\AppData\Roaming\npm\node_modules\node-firestore-import-export\dist\bin
comment this code and directly add your Project ID
`//var projectID = (pathReference._referencePath && pathReference._referencePath._projectId) ||
        //(pathReference.firestore && pathReference.firestore._referencePath && pathReference.firestore._referencePath._projectId);
        // || pathReference.firestore.projectId;
    var projectID = "YOUR_PROJECT_ID";`

this project occurring due to wrong variable name.
