### ISSUE TITLE
Export timestamp [Object] value

### ISSUE THREAD

**Issue by andreescocard** [jloosli/node-firestore-import-export#47]
### Expected behavior
Display the timestamp value: 18 de março de 2019 18:30:00 UTC-3

### Actual behavior
Shows like this:  end: { __datatype__: 'timestamp', value: [Object] },

### Steps to reproduce the behavior
Export using library a collection with timestamp 

Thanks

**Comment by jloosli** [comment]
Firebase stores timestamps, geopoints, and references as special classes (see https://github.com/jloosli/node-firestore-import-export#special-datatypes), so in order to serialize them into something exportable as JSON, I convert them to objects (see https://github.com/jloosli/node-firestore-import-export#data-format). If you're wanting to view them directly from the exported data, you'll need to take the serialized data and convert it into the format you're wanting.
